version: "3"
services:
  fluentd:
    image: fluent/fluentd:v1.16.2-debian-arm64-1.0
    container_name: fluentd
    restart: unless-stopped
    #privileged: true
    #user: ""
    #network_mode: host
    ports:
     - 24224:24224
    #environment:
    #  - 
    volumes:
      - type: bind
        source: fluent.conf
        target: /fluentd/etc/fluent.conf
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    