version: "3"

services:
  loki-read:
    image: grafana/loki:2.8.4-arm64
    container_name: loki-read
    restart: unless-stopped
    #privileged: true
    #user: "1000:1000"
    network_mode: host
    volumes:
      - type: bind
        source: loki-config.yaml
        target: /opt/loki-config.yaml
      #- ./data:/loki
    environment:
      - TZ=Asia/Taipei
    command: -config.file=/opt/loki-config.yaml -target=read

  loki-write:
    image: grafana/loki:2.8.4-arm64
    container_name: loki-write
    restart: unless-stopped
    #privileged: true
    #user: "1000:1000"
    network_mode: host
    volumes:
      - type: bind
        source: loki-config.yaml
        target: /opt/loki-config.yaml
      #- ./data:/loki
    environment:
      - TZ=Asia/Taipei
    command: -config.file=/opt/loki-config.yaml -target=read


  redis:
    image: redis:7.2.1-alpine3.18
    container_name: redis
    network_mode: host
    user: "856710552:856710552"
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./data/redis:/data
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
  
  loki-gateway:
    image: nginx:1.25.2-alpine3.18
    container_name: gateway
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf