version: '3.9'

services:
  metabase:
    image: metabase/metabase-enterprise
    container_name: metabase
    restart: unless-stopped
    init: true
    #network_mode: host
    #user: ""
    ports:
     - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: $POSTGRES_DB
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_ENCRYPTION_SECRET_KEY: /run/secrets/mb_key
      MB_DB_HOST: postgres
      #Listening on a specific network interface
      MB_JETTY_HOST: 0.0.0.0
      #Setting the Java Timezone
      JAVA_TIMEZONE: Asia/Taipei
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    secrets:
      - db_password
      - db_user
      - mb_key
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.70'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    restart: unless-stopped
    #network_mode: host
    #user: ""
    ports:
     - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: ${PGDATA}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    secrets:
      - db_password
      - db_user
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 10s
      retries: 5
secrets:
  db_password:
    file: ./config/db_password.txt
  db_user:
    file: ./config/db_user.txt
  mb_key:
    file: ./config/mb_key.txt