version: "3.8"
services:

  redis_exporter:
    image: quay.io/oliver006/redis_exporter:v1.54.0-alpine
    container_name: redis_exporter
    restart: unless-stopped
    #network_mode: host
    command:
      - '-redis-only-metrics'
    ports:
     - "9121:9121/TCP"
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s