version: "3"
services:
  fluenbit:
    image: fluent/fluent-bit:2.1.8-arm64
    container_name: fluentbit
    restart: unless-stopped
    #user: ""
    #network_mode: host
    ports:
     - 24224:24224
    #environment:
    #  - 
    volumes:
      - type: bind
        source: fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s