version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.47.1
    container_name: prometheus
    restart: unless-stopped
    #network_mode: host
    #user: ""
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
     - 9090:9090
    #environment:
    #  - 
    volumes:
      - ./config/alert.rules:/etc/prometheus/alert.rules:ro
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/targets.yml:/etc/prometheus/targets.yml:ro
      - ./data/prometheus:/prometheus
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  grafana:
    image: grafana/grafana-enterprise:10.1.2
    container_name: grafana
    restart: unless-stopped
    #network_mode: "host"
    #user: ""
    ports:
     - 3000:3000
    #environment:
    #  - 
    volumes:
     # - ./grafana.ini/:/etc/grafana/grafana.ini
      - ./data/grafana:/var/lib/grafana
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    restart: unless-stopped
    #network_mode: host
    #user: ""
    command:
      - '--storage.path=/alertmanager'
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
     - 9093:9093
    #environment:
    #  - 
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./data/alertmanager:/alertmanager
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.24.0
    container_name: blackbox-exporter
    restart: unless-stopped
    #network_mode: host
    command:
      - '--web.listen-address=:9115'
      - '--history.limit=100'
      - '--config.file=/config/blackbox.yml'
    ports:
     - "9115:9115/TCP"
    volumes:
      - ./config/blackbox.yml:/config/blackbox.yml:ro
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s