# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox-2'
    metrics_path: /probe
    scrape_interval: 30s
    scrape_timeout: 30s
    file_sd_configs:
      - refresh_interval: 1s
        files:
        - /etc/prometheus/targets.yml
    relabel_configs:
    # adds "module" label in the final labelset
    - source_labels: [__address__]
      regex: '.*:_:(.*):_:.*:_:.*'
      target_label: module             
    # rewrites "job" label
    - source_labels: [__address__]
      regex: '.*:_:.*:_:(.*):_:.*'
      target_label: job     
    # rewrites "instance" label with corresponding URL
    - source_labels: [__address__]
      regex: '.*:_:.*:_:.*:_:(.*)'
      target_label: instance
    # passes "module" parameter to Blackbox exporter
    - source_labels: [module]
      target_label: __param_module        
    # passes "target" parameter to Blackbox exporter
    - source_labels: [instance]
      target_label: __param_target 
    # the Blackbox exporter's real hostname:port
    - source_labels: [__address__]
      regex: '(.*):_:.*:_:.*:_:.*'
      target_label: __address__       
    