version: '2.4'
services:
  core:
    image: jumpserver/core-ce:${VERSION}
    container_name: jms_core
    ulimits:
      core: 0
    restart: always
    tty: true
    command: start web
    environment:
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      DEBUG: $DEBUG
      LOG_LEVEL: $LOG_LEVEL
      DOMAINS: $DOMAINS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
    healthcheck:
      test: "curl -fsL http://localhost:8080/api/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    logging:
      options:
        max-size: "1024m"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - net

  celery:
    image: jumpserver/core-ce:${VERSION}
    container_name: jms_celery
    ulimits:
      core: 0
    restart: always
    tty: true
    command: start task
    environment:
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      DEBUG: $DEBUG
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    logging:
      options:
        max-size: "1024m"
    networks:
      - net

  koko:
    image: jumpserver/koko:${VERSION}
    container_name: jms_koko
    ulimits:
      core: 0
    restart: always
    privileged: true
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      SSHD_PORT: ${SSH_PORT:-2222}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost:5000/koko/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      options:
        max-size: "1024m"
    volumes:
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT}
    networks:
      - net

  lion:
    image: jumpserver/lion:${VERSION}
    container_name: jms_lion
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost:8081/lion/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      options:
        max-size: "1024m"
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    networks:
      - net

  magnus:
    image: jumpserver/magnus:${VERSION}
    container_name: jms_magnus
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT:-33061}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT:-33062}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT:-63790}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "nc -z 127.0.0.1 33061 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      options:
        max-size: "1024m"
    volumes:
      - ${VOLUME_DIR}/magnus/data:/opt/magnus/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - ${MAGNUS_MYSQL_PORT:-33061}:33061
      - ${MAGNUS_MARIADB_PORT:-33062}:33062
      - ${MAGNUS_REDIS_PORT:-63790}:63790
    networks:
      - net

  chen:
    image: jumpserver/chen:${VERSION}
    container_name: jms_chen
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -f 127.0.0.1:8082/chen"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      options:
        max-size: "1024m"
    networks:
      - net

  kael:
    image: jumpserver/kael:${VERSION}
    container_name: jms_kael
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost:8083/kael/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      options:
        max-size: "1024m"
    networks:
      - net

  web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    restart: always
    tty: true
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/nginx/data/logs:/var/log/nginx
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
    logging:
      options:
        max-size: "1024m"
    networks:
      - net

  redis:
    image: redis:7.2.1-alpine3.18
    container_name: jms_redis
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD --loglevel warning --maxmemory-policy allkeys-lru
    environment:
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 3s
    volumes:
      - ${VOLUME_DIR}/redis/data:/data
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    logging:
      options:
        max-size: "1024m"
    networks:
      - net
  
  mysql:
    image: mysql:8.0.35
    container_name: jms_mysql
    restart: always
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    healthcheck:
      test: "mysql -h127.0.0.1 -P$DB_PORT -uroot -p$DB_PASSWORD -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 3s
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql/
      - ./data/mysql/mysqld:/var/run/mysqld
      - ./mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf:ro
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    logging:
      options:
        max-size: "1024m"
    networks:
      - net


networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $DOCKER_SUBNET