version: "3.8"
services:

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter
    restart: unless-stopped
    #network_mode: host
    command:
      - '-collect.info_schema.tablestats'
    ports:
     - "9104:9104/TCP"
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s