version: '3.8'
services:
  jenkins:
    image: jenkins:v1.0
    container_name: jenkins
    #privileged: true
    #user: ""
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ=Asia/Taipei
      - PLUGINS_FORCE_UPGRADE=true
      - TRY_UPGRADE_IF_NO_MARKER=true
      #- JAVA_OPTS=
    volumes:
      - ./data/jenkins:/var/jenkins_home
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s