version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.19.1-alpine
    container_name: portainer
    restart: unless-stopped
    #network_mode: host
    #command: -c /etc/teleport/teleport.yaml
    ports:
      - "9000:9000"
      - "9443:9443"
      - "8000:8000"
    #environment:
    #  - 
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.70'
        memory: 1G
      reservations:
        cpus: '0.5'
        memory: 512M
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    #healthcheck:
    #  test: ["CMD-SHELL","curl --fail http://localhost:8080/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 10s
    #  retries: 5