version: "3.8"

services:

  timescaledb:
    image: timescale/timescaledb:2.12.0-pg15
    container_name: timescaledb
    #network_mode: "host"
    #user: ""
    ports:
     - "5432:5432/TCP"
    environment:
      TZ: Asia/Taipei
      POSTGRES_DB: timescaledb
      POSTGRES_USER: postgres #postgres
      POSTGRES_PASSWORD: password #1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/timescale:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin