version: "3.8"

services:

  telegraf:
    image: telegraf:1.28.2-alpine
    container_name: telegraf
    #network_mode: "host"
    #user: ""
    ports:
     - "8125:8125/UDP"
     - "8092:8092/UDP"
     - "8094:8094/TCP"
    environment:
      - TZ=Asia/Taipei
     # - HOST_ETC="/hostfs/etc"
     # - HOST_PROC="/hostfs/proc"
     # - HOST_SYS="/hostfs/sys"
     # - HOST_VAR="/hostfs/var"
     # - HOST_RUN="/hostfs/run"
     # - HOST_MOUNT_PREFIX="/hostfs"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576